/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MedicosObjectPageObjectPage journey");

        opaTest("Navigate to MedicosObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheMedicosList.onFilterBar().iExecuteSearch();

            Then.onTheMedicosList.onTable().iCheckRows();
            When.onTheMedicosList.onTable().iPressRow(0);

            Then.onTheMedicosObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheMedicosObjectPage.iCheckSection({ section: "FieldGroup::DatosMedico" });
            Then.onTheMedicosObjectPage.onForm({ section: "FieldGroup::DatosMedico" }).iCheckField({ property: "nombre" });
            Then.onTheMedicosObjectPage.onForm({ section: "FieldGroup::DatosMedico" }).iCheckField({ property: "apellido" });
            Then.onTheMedicosObjectPage.onForm({ section: "FieldGroup::DatosMedico" }).iCheckField({ property: "matricula" });
            Then.onTheMedicosObjectPage.onForm({ section: "FieldGroup::DatosMedico" }).iCheckField({ property: "especialidad_ID" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});