/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TurnosObjectPageObjectPage journey");

        opaTest("Navigate to TurnosObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheMedicosList.onFilterBar().iExecuteSearch();

            Then.onTheMedicosList.onTable().iCheckRows();
            When.onTheMedicosList.onTable().iPressRow(0);

            Then.onTheMedicosObjectPage.iSeeThisPage();
            Then.onTheMedicosObjectPage.onTable({ property: "turnos" }).iCheckRows();
            When.onTheMedicosObjectPage.onTable({ property: "turnos" }).iPressRow(0);

            Then.onTheTurnosObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheTurnosObjectPage.iCheckSection({ section: "FieldGroup::DetalleTurno" });
            Then.onTheTurnosObjectPage.onForm({ section: "FieldGroup::DetalleTurno" }).iCheckField({ property: "paciente_ID" });
            Then.onTheTurnosObjectPage.onForm({ section: "FieldGroup::DetalleTurno" }).iCheckField({ property: "medico_ID" });
            Then.onTheTurnosObjectPage.onForm({ section: "FieldGroup::DetalleTurno" }).iCheckField({ property: "fecha" });
            Then.onTheTurnosObjectPage.onForm({ section: "FieldGroup::DetalleTurno" }).iCheckField({ property: "hora" });
            Then.onTheTurnosObjectPage.onForm({ section: "FieldGroup::DetalleTurno" }).iCheckField({ property: "estado" });
            Then.onTheTurnosObjectPage.onForm({ section: "FieldGroup::DetalleTurno" }).iCheckField({ property: "motivo" });
            Then.onTheTurnosObjectPage.onForm({ section: "FieldGroup::DetalleTurno" }).iCheckField({ property: "observaciones" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});